services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  files:
    image: alpine:3.18
    command: ["sh", "-c", "mkdir -p /srv/files && tail -f /dev/null"]
    volumes:
      - file_storage:/srv/files

  web:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - files
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - file_storage:/app/storage

volumes:
  pg_data:
  file_storage:
