"""Add is_public to FileMetadata

Revision ID: e70ec304d5fc
Revises: de7677f60b56
Create Date: 2025-06-06 23:36:46.844740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70ec304d5fc'
down_revision = 'de7677f60b56'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('file_metadata') as batch_op:
        batch_op.add_column(
            sa.Column(
                'is_public',
                sa.Boolean(),
                nullable=False,
                server_default=sa.true()   # <- add this
            )
        )
    # Now that existing rows are populated with 'true', remove the default:
    with op.batch_alter_table('file_metadata') as batch_op:
        batch_op.alter_column('is_public', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
